version: '0.1.{build}'
image:
  - Visual Studio 2019
configuration: Release
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true

environment:
  appveyor_repo_tag: true

install:

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./SimpleRpc.sln --verbosity m

build_script:
  - cmd: dotnet build ./SimpleRpc.sln -c Release --force
  - cmd: dotnet publish ./SimpleRpc.sln -c Release

after_build:

on_finish:

artifacts:
  - path: .\**\*.nupkg
    name: NuGet

nuget:
  disable_publish_on_pr: true
  project_feed: true

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: l6ItL+x2dkM+zlR4zd30e7Fbs/0Cifp2a2Qoi7OeNvFtxwOvYggSqMMebiXOZMrH
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true